# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('metrics', models.TextField(default='{}')),
                ('calc_status', models.CharField(choices=[('S', 'Started'), ('F', 'Failed'), ('C', 'Completed')], default='STARTED', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
