# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestyle',
            name='calc_status',
            field=models.CharField(choices=[('S', 'Started'), ('F', 'Failed'), ('C', 'Completed')], default='S', max_length=32),
        ),
    ]
