# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_style', '0002_auto_20170601_1115'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepositoryConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_style.CodeStyle')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.GitRepository')),
            ],
        ),
    ]
