# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_gitrepositoryconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='code_style_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
