# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_style', '0002_auto_20170601_1115'),
        ('repository', '0003_gitrepository_code_style_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gitrepositoryconnection',
            unique_together=set([('repository', 'code_style')]),
        ),
    ]
